const DIFFICULTY = 3;
const MINE_RATE = 10000;
const TOLERANCE = 500;
const INITIAL_BALANCE = 200;
const MINING_REWARD = 50;

module.exports = { DIFFICULTY, MINE_RATE, TOLERANCE, INITIAL_BALANCE, MINING_REWARD };